// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SVV.MessagingApp.Data;

namespace SVV.MessagingApp.Migrations
{
    [DbContext(typeof(MessageThreadDbContext))]
    [Migration("20201013174108_AddContactModel")]
    partial class AddContactModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("SVV.MessagingApp.Data.Contact", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("SVV.MessagingApp.Data.Message", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Delivered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MessageThreadID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MessageThreadID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SVV.MessagingApp.Data.MessageThread", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryPhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MessageThreads");
                });

            modelBuilder.Entity("SVV.MessagingApp.Data.Message", b =>
                {
                    b.HasOne("SVV.MessagingApp.Data.MessageThread", null)
                        .WithMany("Messages")
                        .HasForeignKey("MessageThreadID");
                });
#pragma warning restore 612, 618
        }
    }
}
